language: java
jdk:
  - openjdk11
os:
  - linux
cache:
  directories:
    - ~/.m2/repository
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true --quiet --batch-mode --show-version --activate-profiles travis

jobs:
  include:
    - name: "Unit Tests - Cleanup"
      if: type = push
      script:
        - mvn -pl 'beekeeper-cleanup' test
    - name: "Unit Tests - Core"
      if: type = push
      script:
        - mvn -pl 'beekeeper-core' test
    - name: "Unit Tests - Path-Scheduler"
      if: type = push
      script:
        - mvn -pl 'beekeeper-path-scheduler,beekeeper-path-scheduler-apiary' test
    - name: "Integration Tests"
      if: type = pull_request
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'
        - mvn -pl 'beekeeper-integration-tests' test
