language: java
jdk:
  - openjdk11
os:
  - linux
cache:
  directories:
    - ~/.m2/repository
install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true --quiet --batch-mode --show-version --activate-profiles travis

jobs:
  include:
    - name: "Unit Tests"
      script:
        - mvn package --batch-mode --show-version --activate-profiles travis
    - name: "Integration Tests"
      if: type = pull_request
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
        - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./travis/run_on_non_pull_requests; fi'
        - mvn package --batch-mode --show-version --activate-profiles travis


