version: '3.7'
services:
  mysql:
    image: mysql:latest
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=beekeeper
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    ports:
      - '3306:3306'
    expose:
      - '3306'

localstack:
container_name: "${LOCALSTACK_DOCKER_NAME-localstack}"
image: localstack/localstack
hostname: localstack
networks:
  - anynet
ports:
  - "4566:4566"
environment:
  - SERVICES=sqs,sns
  - DEBUG=1
  - DOCKER_HOST=unix:///var/run/docker.sock
  - HOST_TMP_FOLDER=${TMPDIR}
  - HOSTNAME_EXTERNAL=localstack
volumes:
  - ./data:/tmp/localstack
  - "/var/run/docker.sock:/var/run/docker.sock"
