{
 "title": "BDP :: Beekeeper",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  { "title": "Data deleted in time period", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "target": "cumulative(removeBelowValue(derivative(hcom-data-prod.com.hotels.bdp.beekeeper.s3-bytes-deleted.count), 0))"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "target": "cumulative(removeBelowValue(derivative(hcom-data-prod.com.hotels.bdp.beekeeper.s3-bytes-deleted.count), 0))"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "target": "cumulative(removeBelowValue(derivative(hcom-data-prod.com.hotels.bdp.beekeeper.s3-bytes-deleted.count), 0))"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "format": "decbytes",
   "valueName": "total",
   "targets": [
    {
     "target": "cumulative(removeBelowValue(derivative(hcom-data-prod.com.hotels.bdp.beekeeper.s3-bytes-deleted.count), 0))"
    }
   ]
  },
  { "title": "All other metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Bytes deleted",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "alias(removeBelowValue(derivative(hcom-data-prod.com.hotels.bdp.beekeeper.s3-bytes-deleted.count), 0), 'S3 bytes deleted')"
    }
   ]
  },
  {
   "title": "Cleanup job mean duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(hcom-data-prod.com.hotels.bdp.beekeeper.cleanup-job.class.com.expediagroup.beekeeper.cleanup.service.PagingCleanupService.exception.none.method.cleanUp.mean, 'Duration (ms)')"
    }
   ]
  },
  {
   "title": "S3 path deletion mean duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(hcom-data-prod.com.hotels.bdp.beekeeper.s3-paths-deleted.class.com.expediagroup.beekeeper.cleanup.path.aws.S3PathCleaner.exception.none.method.cleanupPath.mean, 'Duration (ms)')"
    }
   ]
  },
  {
   "title": "Scheduled and deleted path count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(hcom-data-prod.com.hotels.bdp.beekeeper.scheduled-paths.class.com.expediagroup.beekeeper.scheduler.service.PathSchedulerService.exception.none.method.scheduleForHousekeeping.count, 'Scheduled')"
    },
    {
     "target": "alias(hcom-data-prod.com.hotels.bdp.beekeeper.s3-paths-deleted.class.com.expediagroup.beekeeper.cleanup.path.aws.S3PathCleaner.exception.none.method.cleanupPath.count, 'Deleted')"
    }
   ]
  },
  {
   "title": "Bytes deleted",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "alias(hcom-data-prod.com.hotels.bdp.beekeeper.s3-bytes-deleted.count, 'S3 bytes deleted total')"
    }
   ]
  },
  {
   "title": "Dry run bytes deleted",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "alias(hcom-data-prod.com.hotels.bdp.beekeeper.dry-run-s3-bytes-deleted.count, 'Dry run S3 bytes deleted')"
    }
   ]
  }
 ]
}