management.endpoints.web.exposure.include: health,info,prometheus

server:
  port: 8080

spring:
  jpa:
    database: default
    hibernate:
      ddl-auto: validate
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
properties:
  beekeeper:
    default-cleanup-delay: P3D
    default-expiration-delay: P30D
    cleanup-page-size: 500
    dry-run-enabled: false
    scheduler-delay-ms: 300000 # 5 minutes
