management.endpoints.web.exposure.include: health,info,prometheus

server:
  port: 8008

spring:
  jpa:
    database: default
    hibernate:
      ddl-auto: validate
    properties.hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
properties:
  cleanup-page-size: 500
  dry-run-enabled: false
  scheduler-delay-ms: 300000 # 5 minutes
  repository-scheduler-cron: '0 0 13 * * ?' # Every day at 1pm
  repository-retention-period-days: 182 # 6 months
